### ISSUE TITLE
Suggestion: Swap order in which loots gets into the inventory

### ISSUE THREAD

**Issue by Laifsyn** [blackd/Inventory-Profiles#114]
when you loot stuff on the floor, it will fill from Bottom Left Corner to the Top right. It would be nice for it to be the other way around, specially so because I currently kinda like to have my inventory in this kind of setup(Ignore the random rubbish because I'm still sorting the locked slots)
![image](https://user-images.githubusercontent.com/99366187/155472163-1424dd1e-04e3-4990-bd36-f622672186e0.png)

**Comment by Laifsyn** [comment]
and when moving from chest to inventory and any other case that I may be unaware of

**Comment by blackd** [comment]
Unfortunately how items enter the inventory is determined by the server.

And detecting the cause for something entering the inventory involves dark magic. The closest thing to that in the moment is keeping the empty slots empty but it involves too many assumptions and doesn't work while the inventory is open because it breaks the assumptions. 



But I guess ability to reverse the positioning of the sort and move is possible so I'll look into that.

**Comment by Laifsyn** [comment]
So what if I install it on my server? or would it break your rule of client-side only?

**Comment by blackd** [comment]
You can install it on the server but it does nothing there.
It implemented to be client side only.

**Comment by Laifsyn** [comment]
Well, client side only is still excellent. Thanks for reply

**Comment by Laifsyn** [comment]
oh, btw. The empty locked inv slots are getting filled when moving from chest. is there an option for it?

**Comment by blackd** [comment]
if it's shift click move is done by the server so I can't really prevent it... or double click


the fast move that the mod introduces however honores the locked slots
there are key bindings that can be configured for move matching/all and throw matching/all

**Comment by Laifsyn** [comment]
oh, ok, thanks~

**Comment by blackd** [comment]
It's already possible to make the sort reverse,

![2022-02-24_10 11 51-final](https://user-images.githubusercontent.com/333840/155485075-a5bd4655-0154-4bc4-a5ce-1e4674b86675.png)
