### ISSUE TITLE
[SUGGESTION] Different lock slots per server/world

### ISSUE THREAD

**Issue by srnyx** [blackd/Inventory-Profiles#12]
I use lock slots so that certain items in my inventory don't get sorted (shulkers, torches, extra food). All of these items are in the right column(s) (usually in the 2 right-most ones).
But, in each server/world, I have different items in different locations, sometimes, some spaces are occupied in 1 server when they aren't in another.

**Example:**
Server 1:
![](https://cdn.tixte.com/uploads/srnyx.needs.rest/kqjl3ws9n9a.png)
Server 2:
![](https://cdn.tixte.com/uploads/srnyx.is-from.space/kqjl50wne9a.png)

As you can see, there are different items in different locations, so I have to change the lock slots every time I switch servers, which is super annoying.

**Comment by blackd** [comment]
Yes I was thinking about locked slots per world/server. And I've done some investigation of the code.
It's possible but the code wasn't designed with that in mind and it will take time. 
But it's definitely on the list.

**Comment by blackd** [comment]
Released in v0.8.2

**Comment by srnyx** [comment]
@blackd how can I make Bungeecord servers have different lock slots?

**Comment by blackd** [comment]
it's not possible to have different locked slots for servers behind a proxy, bugeecord or velocity.
the client doesn't have information about them all it sees is the proxy

**Comment by srnyx** [comment]
> it's not possible to have different locked slots for servers behind a proxy, bugeecord or velocity. the client doesn't have information about them all it sees is the proxy

What if you made a Bungeecord plugin that would send information to the clients? You could also implement more features if you did this. Although, I don't really know how different a mod and a plugin is (probably very different), so it's not that practical (as well as the fact that the server administrators would have to install it).

Does the client get any information about the world names, world seeds, server ports? Basically anything that could differ across Bungeecord servers.

**Comment by blackd** [comment]
Communication between mod and plugin is no problem. So yes if someone develops a plugin to inform the clients about server change I can integrate it with the locked slots.

From point of view of the client switching servers behind a proxy is a dimension change. However going form overworld to overworld doesn't provide useful information. 

The seed is not sent to the clients as part of normal operations but there is a command that returns it. How ever usually it's only available to administrators. 
The world name is server only and I doubt most people bother to change it,
Ports and IPs are hidden by the proxy.

Even if there is a shortcut url for particular server i.e. server4.awesomemc.net the client sees all the servers as that name.

**Comment by ChristopherHaws** [comment]
I created a plugin for spigot based servers that does exactly this for the Xaero World Map mod. It creates a text file in the world directory of each server called `xaeromap.txt` with a random number in it. This number is then sent to the clients over the `xaeroworldmap:main` and `xaerominimap:main` channels everytime a player joins the world or changes dimensions. I would gladly help create a fork of that project to try and make it run on velocity instead of each server and have it also send a packet on a channel for your mod to listen for. Even if we don't make it work on Velocity, your mod could implement similar server side functionality to make it work for fabric based servers and I could add support for your mod to my existing plugin.

You can take a look at the plugin source code here:
https://github.com/ChristopherHaws/mc-xaero-map-spigot

**Comment by blackd** [comment]
the idea of the mod is to be pure client side and so far I haven't received single request for proxied server support. So I'm not sure if the effort required will pay off. 

also there is no point for making server side mod for fabric if what you suggest is supported by the proxy
