### ISSUE TITLE
[Fabric][1.18.2] Incompatibility with Carpet Shulker Stacking

### ISSUE THREAD

**Issue by LarveyOfficial** [blackd/Inventory-Profiles#135]
Seems to not be compatible with the Carpet Shulker Box Stacking. Most likely needs to request from the server (carpet) if that setting is enabled. or maybe have some kind of setting in the mod's settings.

![image](https://user-images.githubusercontent.com/39219859/165863744-39b5ac69-74d1-4b92-b9f3-a8b5fa201438.png)
![image](https://user-images.githubusercontent.com/39219859/165863748-39104c5a-243c-4f00-80cc-2a51a7ca85bf.png)

**Comment by blackd** [comment]
works as intended. IPN is 100% client side by design. This guarantees the mod will work the same way on any server. 

over stacked items are ignored during sort this makes it impossible to reorganise in columns or rows because we can't cleat the space needed by those.

IPN works by simulating clicks over stacked items break the normal click behaviour.
