### ISSUE TITLE
Auto Refill doesnt replace from hotbar

### ISSUE THREAD

**Issue by kaiden-lcfc** [blackd/Inventory-Profiles#147]
I'm not sure if this is intentional or not but i would like a setting in the config to auto refill from hotbar as when throwing items out i can repeatedly click ctrl+q on the item in my hotbar and it will be replaced but then it doesnt replace with items from hotbar only inventory so please fix this or add a setting in the config

**Comment by blackd** [comment]
not refilling from the hotbar is the intended behaviour.

**Comment by kaiden-lcfc** [comment]
would it be possible to add a setting in the config to allow that?

**Comment by blackd** [comment]
can you describe your uses case
in which situation will it be more beneficial then to just switch to the other slot

**Comment by diyudule** [comment]
Hello, sometimes I encounter this situation in the picture. After I use up the durability of the tools in the No. 1 grid, I hope that the tools in the No. 3 grid can be automatically replaced in the No. 1 grid, which is convenient for me. To keep working instead of moving the select box, can you add a setting option to the config file even though the option is off by default?
![QQ图片20220712180518](https://user-images.githubusercontent.com/29426186/178476948-62cba106-3409-416f-a74d-4d45ab71621f.png)

**Comment by blackd** [comment]
this behaviour is intentional.

this mod have always left the hotbar alone unchanged
all action that touch the hotbar require explicit user input to do so

**Comment by diyudule** [comment]
ok, thanks for your reply.
