### ISSUE TITLE
Setting to switch to an effective tool on click

### ISSUE THREAD

**Issue by NatoBoram** [blackd/Inventory-Profiles#21]
Hi! I made a small mod a while ago that allowed me to swap item for the most effective one when clicking on a block [here](https://gitlab.com/NatoBoram/fabric-switcheroo). However, Minecraft's code changes a lot and I don't really have time to maintain it properly. I also don't know Java and OOP.

With the wide range of features your mod has, I thought it would be a good idea to have this feature integrated into it.

Here's the workflow I had : 

* Swap to *least effective* but *still working* tool when clicking on a block or mob
  * Swap to *most effective* if holding Sprint key
  * Don't swap if holding Sneak key

I think the integration with Sprint/Sneak is an intuitive one; Sprint is to go fast despite the hunger cost and Sneak is to be careful to not fall a cliff.

Other interesting settings : 

* Swap to using hand if held item is enchanted and has 1 durability, but break it if sneak is held
* Use place block on farmland when breaking the above crop using this crop's seed

cc https://github.com/jsnimda/Inventory-Profiles/issues/34

**Comment by blackd** [comment]
### On the surface it makes sense... BUT

#### Trying to define "most effective" doesn't yield a definitive answer.
- is Silk Touch + Efficiency 3 more effective for grass then Fortune + Efficiency 5
- sometimes you might just want to break something by hand

#### Control scheme that relies on modifying sneak and sprint can have unforeseen consequences.
- what if people have them on toggle. Just to remind you toggle is possible because there are people that might find it hard to press multiple buttons at the same time.
- there are multiple reasons to be sneaking and running and the proposed scheme conflicts with some of them

### Conclusion
I will need more input from multiple sources if I'm to implement something like this

**Comment by blackd** [comment]
@NatoBoram I see your mod is starting to get some traction do you still want me to implement this?

**Comment by NatoBoram** [comment]
If you found a satisfying way to do it, sure!

**Comment by KraXen72** [comment]
if you want this feature, it already exists in tweakeroo, which is maintained.

**Comment by blackd** [comment]
I decided that this is outside the main objective of this mod. And since there are alternatives implementing it here is pointless.
