### ISSUE TITLE
My inventory becomes messy when IPR works with AE2 terminal

### ISSUE THREAD

**Issue by zyxkad** [blackd/Inventory-Profiles#260]
Before:
<img width="1624" alt="Screen Shot 2023-01-03 at 7 12 24 AM" src="https://user-images.githubusercontent.com/91082411/210374129-d32019a4-0872-459f-8512-37a2f8fad035.png">

After:
<img width="1624" alt="Screen Shot 2023-01-03 at 7 12 32 AM" src="https://user-images.githubusercontent.com/91082411/210374160-c30aef92-976f-4cad-9087-ea1aa2c5ae5a.png">

**Comment by zyxkad** [comment]
And I don't know why IPR will sort item when I typing in JEI (my key binding is 'R', when I typing 'R' in GUI any where, the inventory will be sorted)

**Comment by blackd** [comment]
which modpack is this?

Detecting that you type in JEI search box is not trivial

me2 terminals should be ignored by the mod so either they changed something or you use old version of IPN


if the settings haven't been changed r+g will open an ui the will allow you to disable IPN for m2 terminal

Set ignore for the container to true.

for future support questions please use our discord server.

**Comment by zyxkad** [comment]
> me2 terminals should be ignored by the mod so either they changed something or you use old version of IPN

I'm using 1.8.6, I will update to 1.9.1 and reply to you later

**Comment by blackd** [comment]
1.8.6 is new enough so probably me2 changed something and IPN no longer detects their ui

**Comment by zyxkad** [comment]
> 1.8.6 is new enough so probably me2 changed something and IPN no longer detects their ui

Yes is still happen in 1.9.1

> Set ignore for the container to true.

I'm sorry, I don't know how to do that

**Comment by blackd** [comment]
> if the settings haven't been changed r+g will open an ui the will allow you to disable IPN for m2 terminal

press r+g

**Comment by zyxkad** [comment]
> > if the settings haven't been changed r+g will open an ui the will allow you to disable IPN for m2 terminal
> 
> press r+g

Got that, thanks

**Comment by zyxkad** [comment]
> > if the settings haven't been changed r+g will open an ui the will allow you to disable IPN for m2 terminal
> 
> press r+g

But before I press r+g, the inventory will be sorted, weird
Guess you are listening KEYDOWN for 'R'
Should you listen KEYUP?

**Comment by Mari023** [comment]
> 1.8.6 is new enough so probably me2 changed something and IPN no longer detects their ui

@blackd how does Inventory-Profiles detect if it shouldn't sort in a screen?

ae2wtlib replaces this specific screen, which may be why the fix for ae2 doesn't work.
is there anything I can do to fix / disable sorting on that screen?

**Comment by blackd** [comment]
if you read the comments you will know how

**Comment by Mari023** [comment]
while the comments tell me how to change this as an individual user, that isn't what I meant, maybe I should have clarified that.

I am the author of ae2wtlib, and I would like this issue to get fixed in general without every user having to configure this manually.
looking at the code, it seems like this is how the screens are detected?
https://github.com/blackd/Inventory-Profiles/blob/all-in-one/shared-sources/src/main/resources/assets/inventoryprofilesnext/config/ModIntegrationHintsNG.json

however I don't know how the format works, otherwise I would PR this.
is looks like the classname of the screen is used as a key for the configuration?

in that case the relevant screens are 
```
de.mari_023.ae2wtlib.wct.WCTScreen
```
```
de.mari_023.ae2wtlib.wet.WETScreen
```
```
de.mari_023.ae2wtlib.wat.WATScreen
```
there is also a configuration sub screen, which might interact weirdly with sorting
```
de.mari_023.ae2wtlib.wct.magnet_card.config.MagnetScreen
```

**Comment by blackd** [comment]
check out this PR https://github.com/blackd/Inventory-Profiles/pull/384
