### ISSUE TITLE
Implement hotbar cycling [Stardew valley style]

### ISSUE THREAD

**Issue by EthanZeigler** [blackd/Inventory-Profiles#306]
## Ask

Implement stardew valley's hotbar swapping functionality to a hotkey. Pressing this hotkey moves each item in the player's inventory down one "row", wrapping the hotbar back up to the top row of the inventory. 

This drastically increases the player's ability to access items from their inventory quickly without needing to shuffle around items and is great if you need something from the backpack "real quick"

## Technicalities

For locked slots, i'd recommend skipping that cell in the inventory. If the hotbar slot 1 is locked, for instance, shift the rest of the player inventory for that column rolling over the locked slots.

**Comment by blackd** [comment]
https://www.curseforge.com/minecraft/mc-mods/hotbarcycle/

something like this?

**Comment by EthanZeigler** [comment]
That works, yep lol. Nevertheless it would be a good feature for ipn

**Comment by blackd** [comment]
I don't want to steal features from small mods. :)

**Comment by TheOverpassArsonist** [comment]
> I don't want to steal features from small mods. :)

I wouldn't consider this 'stealing a feature' as it's just re-implementing a rather common mechanic. (IIRC even vanilla has something like this with the creative toolbars thing, though I've never bothered using them myself) Personally I just don't really think implementing a super common mechanic like this would be 'stealing' anything; though I don't make mods personally so admittedly my word probably isn't worth much here. Still though it feels odd to say it's 'stealing' a feature when even most mods that do implement it describe it in terms of other things that have already implemented it (such as Stardew Valley)

With that said, if it is still a gripe, I think hotswapping single items would also be a good system that's semi-rarely implemented and stays decently far away from stepping on any other (actively maintained) mod's toes. The last mod that I've been able to find to implement something like it was [this](https://www.curseforge.com/minecraft/mc-mods/inventory-hotswap) (last updated in 2023 according to curseforge, 19.4) and, personally, it's my preferred system for this sort of thing. It's probably the one mod I miss the most on 1.20.1 so far and I'm not aware of any smooth replacements for it on modern versions.

It's juuuuust close enough to hotbar-swapping for me to think it'd technically qualify as the same feature (hence why I'm replying here rather than making a new issue) but it's definitely still a distinct thing that wouldn't be 'stealing' from any (actively maintained) mods. (that I'm aware of at least)
