### ISSUE TITLE
Switching profiles cannot switch from body to hotbar

### ISSUE THREAD

**Issue by DashinBoi** [blackd/Inventory-Profiles#317]
EG: wear elytra, then switch to a profile where the elytra is in the hotbar. 

If the slot where the elytra is in the hotbar also has a chestplate, double pressing the bind will unequip the elytra, and then move it from inventory to hotbar.

Edit: 
Slight error, this only occurs if the profile that swaps the elytra for a chestplate also has an item in the inventory slot that you're attempting to move the elytra to. (probably something weird in how to code is executed) I'll attach the profiles file I'm using. 
[profiles.txt](https://github.com/blackd/Inventory-Profiles/files/11175980/profiles.txt)

**Comment by blackd** [comment]
So you have a profile that has elytra in slot X and expect when you switch from a profile that has elytra in the chest slot the same elytra to end in slot X?

This won't work because the items from the old profile are not considered for use in the new one. the second attempt to apply the profile will be successful because the elytra is no longer part of the profile.

This works that way to avoid some infinite loop possibilities.

**Comment by DashinBoi** [comment]
So an issue that is created to avoid an issue of significantly greater importance. 

Understandable, and I’m the grand scheme of things, it’s probably gonna get noticed by one or two people, and the fix it literally just clicking twice anyway.
