### ISSUE TITLE
Blinking buttons when hover

### ISSUE THREAD

**Issue by xhaooy** [blackd/Inventory-Profiles#319]
hi, all buttons related to this mod blink when hover(in inventory, crafting table). in furnance it doesnt show "move matching items" text.
i have installed rei and exordium(if that information help).

**Comment by blackd** [comment]
can you specify which version of the mod and which mod loader
and full list of installed mods

**Comment by xhaooy** [comment]
InventoryProfilesNext-fabric-1.19-1.9.5 downloaded from curseforge, fabric 0.14.19
https://pastebin.com/Pu9fmMe8

**Comment by blackd** [comment]
So I can confirm the blinking on 1.19.2 but it doesn't appear in 1.19.4 which has newer version of exordium
I suggest you report this to exordium since it's their magic that causes it and they clearly changed something in 1.19.4 to fix it.

About furnace gui no inventory manipulation buttons are added to that gui,
