### ISSUE TITLE
Support for empty slots as part of a profile.

### ISSUE THREAD

**Issue by cibere** [blackd/Inventory-Profiles#59]
please support empty slots. I mainly use this mod to have two saved hotbars. Normal and PVP. When I use pvp, my shield goes into my off hand, but when i go back to normal my shield stays there even though I want it to go into my inventory.

**Comment by blackd** [comment]
also to add configuration to prefer empty locked slots as target for swapping the item from the empty profile slot.

this might be harder to do if so this feature will probably be released in 2 parts.

**Comment by e-motiv** [comment]
Apparently this is possible since "Done", but after one hour of searching I still can't figure out how to empty my offhand via a profile.  I tried the following after OFFHAND:  "" (empty string) / "minecraft:air" /    (nothing)

Can you add how to set a slot empty in the doc. please? Or is this a bug?

In the changelog it says "Just add the slot name without items in the configuration". I did that, doesn't work.
There are free slots in my inventory, also free locked slots.
```
    profile Edit activate HOT3
    HOT1
    		"minecraft:wooden_axe"
    	HOT2
    		"minecraft:wooden_pickaxe"
    	HOT3
    		"minecraft:stick"
    	HOT4
    		"minecraft:golden_axe"
    	HOT5
    		"minecraft:compass"
    	HOT8
    		"minecraft:dirt"
    	HOT9
    		"minecraft:apple"
    	OFFHAND
```
forge-1.19.2-43.1.25
IPN 1.7.1

**Comment by blackd** [comment]
please don't use the issue tracker for support questions 

ask on discord or r/InventoryProfilesNext subreddit 

here is how to do it 
```
profile Naked
    HEAD
    CHEST
    LEGS
    FEET
```
