### ISSUE TITLE
Bad glitches with AE2

### ISSUE THREAD

**Issue by ghost** [blackd/Inventory-Profiles#68]
So when you search in the AE2 system it picks up blank pattern items and the sorting buttons obscure the search bar. The blank pattern pickup stops when inventory profiles next is removed.

See the video here [https://skb.brads.computer/2021-11-12%2019-12-14.mkv](https://skb.brads.computer/2021-11-12%2019-12-14.mkv)

Its just really not compatible with applied energistics 2, is there a way to make it so that the invetory profiles next mod doesn't enable itself with the AE2 system? Or make it a config option to turn it off inside of the AE2 system?

**Comment by blackd** [comment]
Hi this is better to be handled in AE2 using this mod API. Can you please open issue there. 
And link it here  https://github.com/blackd/Inventory-Profiles/issues/54 so I can track their decision.

If they refuse I will add their UI in the configuration. But I prefer if they handle this because it will be easier for them to maintain it properly.

**Comment by blackd** [comment]
#82
