### ISSUE TITLE
[1.18.1-Forge] java.lang.NullPointerException when joining server. (java.net.UnknownHostException: ipn.anti-ad.org) ?

### ISSUE THREAD

**Issue by Gbergz** [blackd/Inventory-Profiles#84]
Title^ 

One of my users of my servers reported this.
Currently I do not have this issue myself.

Minecraft: 1.18.1
Forge: 39.0.5
Inventory Profiles: 1.2.1

Part of log when getting disconnected: https://gist.github.com/Gbergz/141ff9a65d76adee0054757a67c1e40a

**Comment by blackd** [comment]
Hi can I get the full log?
because the exception you posted cannot cause problems since it's executed in separate thread and just checks if there is new version.

**Comment by Gbergz** [comment]
I'll get it for you soon

**Comment by Gbergz** [comment]
[latest.log](https://github.com/blackd/Inventory-Profiles/files/7775734/latest.log)

Here you go

**Comment by blackd** [comment]
I've tested with the currently published version of TNP Limitless 5 and disabled internet.
* the exception is just a dump when something goes wrong with checking for updates.
* I guess it will be better to change it to a more descriptive message instead of full exception.
* other then the dump the mod is functioning properly,

As for why you cant resolve the name, if you haven't explicitly done something that prevents Minecraft from resolving it I suggest you check with your ISP

**Comment by Gbergz** [comment]
Hm, alright. I guess disabling checking for updates would solve this?

**Comment by blackd** [comment]
Well no. 
Due to how the code is separated in common and loader/version specific currently the the check is always done. And the message to the user can be disabled.

If you really need it disabled now, the change to not print the exception is single row of code. And I can push a new version in about an hour (this is how long it take to github to build and publish it)

Or you can wait the next feature update probably the end of January.

**Comment by Gbergz** [comment]
Gotcha!

> If you really need it disabled now, the change to not print the exception is single row of code. And I can push a new version in about an hour

That would be nice.

**Comment by blackd** [comment]
fixed b901a34 and released
