### ISSUE TITLE
Trim the release note to just the relevant part of the changelog

### ISSUE THREAD

**Issue by NatoBoram** [blackd/Inventory-Profiles#88]
It's very cool that there's a proper [changelog](https://github.com/blackd/Inventory-Profiles/blob/all-in-one/changelog.md) and a very accessible [releases](https://github.com/blackd/Inventory-Profiles/releases) page, but copying the whole changelog on every releases is a bit much.

Is it possible to add something like this to the GitHub Action?

```sh
begin=$(grep -n '<!-- latest begin -->' changelog.md | cut -f1 -d:)
end=$(grep -n '<!-- latest end -->' changelog.md | cut -f1 -d:)
sed -n "$begin , $end p" changelog.md
```

It gives me this output:

```md
<!-- latest begin -->

### 1.2.2 - just a hotfix 
- fixed typo.
- removed a debug dump that looked like it's something important.
- added forge 1.15.2 version 

<!-- latest end -->
```

**Comment by blackd** [comment]
My intend was to do something like [description](https://github.com/blackd/Inventory-Profiles/tree/all-in-one/description) generation for the release action too. With more information about the changes and probably screenshots an so on..

I guess I'll never do it because providing full documentation for the new features in the release notes takes too much time.

Just trimming the change log will have to do...

**Comment by blackd** [comment]
On other note.. I never expected anyone to get to the github release page so I never really cared much about making them pretty :smile:

**Comment by NatoBoram** [comment]
Thanks!
